summary: build spread from specific branches

systems: [ubuntu-20.04-64]

environment:
    GOVERSION: latest/stable
    GOHOME: /home/test
    GOPATH: $GOHOME
    SPREAD_PATH: $GOHOME/src/github.com/snapcore/spread
    SPREAD_URL: https://github.com/sergiocazzolato/spread.git
    SPREAD_BRANCH/harcoded_ssh_key: harcoded-ssh-key
    SPREAD_NAME/harcoded_ssh_key: fixedkey
    SPREAD_BRANCH/debug: debug-version
    SPREAD_NAME/debug: debug
    SPREAD_BRANCH/arm: update-google-startup-script
    SPREAD_NAME/arm: arm
    SPREAD_BRANCH/openstack: migrate-openstack-backend
    SPREAD_NAME/openstack: openstack
    SPREAD_ARCH: amd64
    SPREAD_FILE: spread-$SPREAD_NAME-$SPREAD_ARCH
    SPREAD_EXEC: spread-$SPREAD_NAME
    PATH: $GOHOME/bin:$PATH

prepare: |
    # Download spread code
    apt install -y git
    rm -rf "$GOHOME"/src/github.com/snapcore/spread
    mkdir -p "$SPREAD_PATH"
    git clone "$SPREAD_URL" "$SPREAD_PATH"
    (cd "$SPREAD_PATH" && git checkout "$SPREAD_BRANCH")

    # Install go dependencies
    snap install go --classic --channel "$GOVERSION"

    # Prepare to upload files to gs bucket
    if ! command -v gcloud &>/dev/null; then
        snap install --classic google-cloud-sdk
    fi
    gcloud auth activate-service-account --key-file="$PROJECT_PATH/sa.json"

restore: |
    rm -rf godeb spread
    rm -f "$SPREAD_PATH"/"$SPREAD_FILE".tar.gz
   
execute: |
    # Build spread
    export GO111MODULE=off
    go get "$SPREAD_PATH"/cmd/spread

    # Check spread is created and it is executable
    test -x "$GOHOME"/bin/spread
    mv "$GOHOME"/bin/spread "$GOHOME"/bin/"$SPREAD_EXEC"

    # Back up previous spread if it is published
    if gsutil ls gs://snapd-spread-tests/spread/"$SPREAD_FILE".tar.gz; then
        gsutil cp gs://snapd-spread-tests/spread/"$SPREAD_FILE".tar.gz gs://snapd-spread-tests/spread/"$SPREAD_FILE"-old.tar.gz
    fi

    # Prepare tmp spreadand push to gce bucket
    tar -czf ./"$SPREAD_FILE".tar.gz --directory="$GOHOME"/bin "$SPREAD_EXEC"
    if gsutil ls gs://snapd-spread-tests/spread/"$SPREAD_FILE"-tmp.tar.gz; then
        gsutil rm gs://snapd-spread-tests/spread/"$SPREAD_FILE"-tmp.tar.gz
    fi
    gsutil cp "$SPREAD_FILE".tar.gz gs://snapd-spread-tests/spread/"$SPREAD_FILE"-tmp.tar.gz

    # check spread is executable and works
    wget https://storage.googleapis.com/snapd-spread-tests/spread/"$SPREAD_FILE"-tmp.tar.gz
    tar -xvzf "$SPREAD_FILE"-tmp.tar.gz
    test -x ./"$SPREAD_EXEC"
    ./"$SPREAD_EXEC" -h 2>&1 | MATCH "Usage of"

    # Finally replace the new spread
    if gsutil ls gs://snapd-spread-tests/spread/"$SPREAD_FILE".tar.gz; then
        gsutil rm gs://snapd-spread-tests/spread/"$SPREAD_FILE".tar.gz
    fi
    gsutil mv gs://snapd-spread-tests/spread/"$SPREAD_FILE"-tmp.tar.gz gs://snapd-spread-tests/spread/"$SPREAD_FILE".tar.gz
