summary: Update the gce test bucket

prepare: |
    snap install google-cloud-sdk
    gcloud auth activate-service-account --key-file="$PROJECT_PATH/sa.json"
    rm -f "$PROJECT_PATH/sa.json"

restore: |
    rm -f *.img
    snap remove google-cloud-sdk || true
   
execute: |
    wget -q "https://cloud-images.ubuntu.com/xenial/current/xenial-server-cloudimg-amd64-disk1.img"
    gsutil cp xenial-server-cloudimg-amd64-disk1.img gs://snapd-spread-tests/images/cloudimg/

    wget -q "https://cloud-images.ubuntu.com/bionic/current/bionic-server-cloudimg-amd64.img"
    gsutil cp bionic-server-cloudimg-amd64.img gs://snapd-spread-tests/images/cloudimg/

    wget -q "https://cloud-images.ubuntu.com/focal/current/focal-server-cloudimg-amd64.img"
    gsutil cp focal-server-cloudimg-amd64.img gs://snapd-spread-tests/images/cloudimg/

    wget -q "https://cloud-images.ubuntu.com/groovy/current/groovy-server-cloudimg-amd64.img"
    gsutil cp groovy-server-cloudimg-amd64.img gs://snapd-spread-tests/images/cloudimg/

    wget -q "https://cloud-images.ubuntu.com/hirsute/current/hirsute-server-cloudimg-amd64.img"
    gsutil cp hirsute-server-cloudimg-amd64.img gs://snapd-spread-tests/images/cloudimg/

    wget -q "https://cloud-images.ubuntu.com/impish/current/impish-server-cloudimg-amd64.img"
    gsutil cp impish-server-cloudimg-amd64.img gs://snapd-spread-tests/images/cloudimg/
