summary: Update the gce test bucket

prepare: |
    for _ in $(seq 60); do
        if snap list google-cloud-cli; then
            snap remove google-cloud-cli || true
        else
            break
        fi
        sleep 1
    done

    if ! command -v gcloud &>/dev/null; then
        snap install --classic google-cloud-sdk
    fi
    gcloud auth activate-service-account --key-file="$PROJECT_PATH/sa.json"
    rm -f "$PROJECT_PATH/sa.json"

restore: |
    rm -f *.img
    snap remove google-cloud-sdk || true
   
execute: |
    wget -q "https://cloud-images.ubuntu.com/xenial/current/xenial-server-cloudimg-amd64-disk1.img"
    gsutil cp xenial-server-cloudimg-amd64-disk1.img gs://snapd-spread-tests/images/cloudimg/

    wget -q "https://cloud-images.ubuntu.com/bionic/current/bionic-server-cloudimg-amd64.img"
    gsutil cp bionic-server-cloudimg-amd64.img gs://snapd-spread-tests/images/cloudimg/

    wget -q "https://cloud-images.ubuntu.com/focal/current/focal-server-cloudimg-amd64.img"
    gsutil cp focal-server-cloudimg-amd64.img gs://snapd-spread-tests/images/cloudimg/

    wget -q "https://cloud-images.ubuntu.com/jammy/current/jammy-server-cloudimg-amd64.img"
    gsutil cp jammy-server-cloudimg-amd64.img gs://snapd-spread-tests/images/cloudimg/

    wget -q "https://cloud-images.ubuntu.com/kinetic/current/kinetic-server-cloudimg-amd64.img"
    gsutil cp kinetic-server-cloudimg-amd64.img gs://snapd-spread-tests/images/cloudimg/
